### ISSUE TITLE
HAL HCD and PCD modules are missing in stm32c0xx_hal_conf_template.h

### ISSUE THREAD

**Issue by fpistm** [STMicroelectronics/stm32c0xx-hal-driver#1]
Since STM32C071xx has been released, USB is supported but HAL HCD an PCD are missing in the [stm32c0xx_hal_conf_template.h
](https://github.com/STMicroelectronics/stm32c0xx-hal-driver/blob/main/Inc/stm32c0xx_hal_conf_template.h)

```c
#define HAL_PCD_MODULE_ENABLED
#define HAL_HCD_MODULE_ENABLED 
```

```c
#ifdef HAL_PCD_MODULE_ENABLED
 #include "stm32c0xx_hal_pcd.h"
#endif /* HAL_PCD_MODULE_ENABLED */

#ifdef HAL_HCD_MODULE_ENABLED
 #include "stm32c0xx_hal_hcd.h"
#endif /* HAL_HCD_MODULE_ENABLED */
```

**Comment by ALABSTM** [comment]
Hi @fpistm,

You're absolutely right. But, good news, this has been fixed in the frame of release **1.3.0** published around two weeks ago.

With regards,
